version: "3.7"

services:
  revcord:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/lib/docker/volumes/revcord/revcord.sqlite:rw
      - ./.env:/app/.env
    env_file:
      - stack.env
    restart: unless-stopped

volumes:
  revcord:
    name: revcord
